# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contentserver < Formula
  desc "Serves content tree structures very quickly"
  homepage "https://github.com/foomo/contentserver"
  version "1.16.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentserver/releases/download/v1.16.0/contentserver_1.16.0_darwin_amd64.tar.gz"
      sha256 "cca827a0d954575dabe1dd4d64c69f1676d84e658e23489ab22f1736878d7f67"

      def install
        bin.install "contentserver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/contentserver/releases/download/v1.16.0/contentserver_1.16.0_darwin_arm64.tar.gz"
      sha256 "0c28bec76a5063444465a83b85ce901580344b78d0d95da78e10dc24bc0f5696"

      def install
        bin.install "contentserver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/contentserver/releases/download/v1.16.0/contentserver_1.16.0_linux_amd64.tar.gz"
      sha256 "9825687d6b13bcd7c70423d51af3dabbb3a89f38fe49b78f8930388e6790fa51"
      def install
        bin.install "contentserver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/contentserver/releases/download/v1.16.0/contentserver_1.16.0_linux_arm64.tar.gz"
      sha256 "f6ffe82cf42629c5d897952ca346bf43febdedecc471b4076a2a765945e7b264"
      def install
        bin.install "contentserver"
      end
    end
  end

  def caveats
    <<~EOS
      contentserver --help
    EOS
  end

  test do
    system "#{bin}/contentserver version"
  end
end
