# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Contentfulcommander < Formula
  desc "A toolbox of non-trivial Contentful interactions"
  homepage "https://github.com/foomo/contentfulcommander"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/contentfulcommander/releases/download/v0.7.1/contentfulcommander_0.7.1_darwin_amd64.tar.gz"
      sha256 "d5c8da30510184ba44e9034bd3e76bbe48cfa78e4ed38a7d57915e5c302d69ed"

      define_method(:install) do
        bin.install "contentfulcommander"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/contentfulcommander/releases/download/v0.7.1/contentfulcommander_0.7.1_darwin_arm64.tar.gz"
      sha256 "2e5b9312eb38fbf34eee8d5db9967aebdb8bcf35576e84d670d1404b337a7d26"

      define_method(:install) do
        bin.install "contentfulcommander"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/contentfulcommander/releases/download/v0.7.1/contentfulcommander_0.7.1_linux_amd64.tar.gz"
      sha256 "fc667acd4ccf0212a6760854aa5f0d643ae1153aca4fe425aa11f1a55327fca9"
      define_method(:install) do
        bin.install "contentfulcommander"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/contentfulcommander/releases/download/v0.7.1/contentfulcommander_0.7.1_linux_arm64.tar.gz"
      sha256 "214c268730858ab0ae638653253091cdeabcc72d25eeee2bca0bc849c62cdc11"
      define_method(:install) do
        bin.install "contentfulcommander"
      end
    end
  end

  def caveats
    <<~EOS
      contentfulcommander help
    EOS
  end
end
