# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockprox < Formula
  desc "Security configuration scanner for developer environments"
  homepage "https://github.com/foomo/dockprox"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/dockprox/releases/download/v0.9.1/dockprox_0.9.1_darwin_amd64.tar.gz"
      sha256 "17e194e5e5fa1c2a02d202648c3049c30172b99a80422da7546896b366d0de21"

      define_method(:install) do
        bin.install "dockprox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/dockprox/releases/download/v0.9.1/dockprox_0.9.1_darwin_arm64.tar.gz"
      sha256 "558efd025e401887acf13bed03fafe59458dbe9fc938808dd14c614e4f96b801"

      define_method(:install) do
        bin.install "dockprox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/dockprox/releases/download/v0.9.1/dockprox_0.9.1_linux_amd64.tar.gz"
      sha256 "e26e77f6a4013ccc2cb6d4f511c5c00d6cf00332af439ec74a9100e6dd9712f0"
      define_method(:install) do
        bin.install "dockprox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/dockprox/releases/download/v0.9.1/dockprox_0.9.1_linux_arm64.tar.gz"
      sha256 "e6f0f87dd9b4ce04001387e8c6b5dfc66bf8ee559f72b39fc884608e4d229990"
      define_method(:install) do
        bin.install "dockprox"
      end
    end
  end

  def caveats
    <<~EOS
      dockprox
    EOS
  end
end
