# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockprox < Formula
  desc "Security configuration scanner for developer environments"
  homepage "https://github.com/foomo/dockprox"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/dockprox/releases/download/v0.6.0/dockprox_0.6.0_darwin_amd64.tar.gz"
      sha256 "4f1d18c7703ca56a6413b23cf66427a74f4af4c3c0184c9fca9060de90795431"

      define_method(:install) do
        bin.install "dockprox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/dockprox/releases/download/v0.6.0/dockprox_0.6.0_darwin_arm64.tar.gz"
      sha256 "296a1120c66fbf543566ba9cdf9f43124c33971baa53085202720ddf391c52ff"

      define_method(:install) do
        bin.install "dockprox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/dockprox/releases/download/v0.6.0/dockprox_0.6.0_linux_amd64.tar.gz"
      sha256 "98768edb94f613afc85212fc416ff03869d38e5c8929ceb11a741cf47cb0f84a"
      define_method(:install) do
        bin.install "dockprox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/dockprox/releases/download/v0.6.0/dockprox_0.6.0_linux_arm64.tar.gz"
      sha256 "b4706593b973d3c8b9baf0eebad7d8b4a59f5798ee445255d0fb5c3d3252d7e4"
      define_method(:install) do
        bin.install "dockprox"
      end
    end
  end

  def caveats
    <<~EOS
      dockprox
    EOS
  end
end
