# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocontentful < Formula
  desc "A Contentful Entry-Reference Mapper for Go"
  homepage "https://github.com/foomo/gocontentful"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gocontentful/releases/download/v1.2.2/gocontentful_1.2.2_darwin_amd64.tar.gz"
      sha256 "a4e3b03cb4eb9104e6173d77092ec35bd9999e289498718b62b919cd88b82cfe"

      def install
        bin.install "gocontentful"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gocontentful/releases/download/v1.2.2/gocontentful_1.2.2_darwin_arm64.tar.gz"
      sha256 "28cf22ba896a6ec3aff51af630ac2928c5c9e4451024712dfe0697d4b4239865"

      def install
        bin.install "gocontentful"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gocontentful/releases/download/v1.2.2/gocontentful_1.2.2_linux_amd64.tar.gz"
      sha256 "4652b014597ad2300d2428e3c8a9ad1978b21e02830ab7c894e01e6ef5c2ea6d"
      def install
        bin.install "gocontentful"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gocontentful/releases/download/v1.2.2/gocontentful_1.2.2_linux_arm64.tar.gz"
      sha256 "ea28205a4323f9a5e5473d8f25500dc3f383f74973bac57a8a60766794d0a6b6"
      def install
        bin.install "gocontentful"
      end
    end
  end

  def caveats
    <<~EOS
      gocontentful -h
    EOS
  end

  test do
    system "#{bin}/gocontentful --version"
  end
end
