# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocontentful < Formula
  desc "An Contentful Entry-Reference Mapper for Go"
  homepage "https://github.com/foomo/gocontentful"
  version "1.1.0-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gocontentful/releases/download/v1.1.0-rc.1/gocontentful_1.1.0-rc.1_darwin_amd64.tar.gz"
      sha256 "7f49c7b9aaba858dba3cf232ff26a04ade0620253ccb24011784c2e831f15274"

      def install
        bin.install "gocontentful"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gocontentful/releases/download/v1.1.0-rc.1/gocontentful_1.1.0-rc.1_darwin_arm64.tar.gz"
      sha256 "e0d654c6fc7320f355b2dbba8608a944b6dfd8cb2ea6c685075484ca09387603"

      def install
        bin.install "gocontentful"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gocontentful/releases/download/v1.1.0-rc.1/gocontentful_1.1.0-rc.1_linux_amd64.tar.gz"
      sha256 "16049b51f82ffc851d25d508167b874dacf4f3396e27c60d7a40035ced45116c"

      def install
        bin.install "gocontentful"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gocontentful/releases/download/v1.1.0-rc.1/gocontentful_1.1.0-rc.1_linux_arm64.tar.gz"
      sha256 "f88311edac44b270e604ac94418a8a68d535bedadb1cc538df43a5adbebdb454"

      def install
        bin.install "gocontentful"
      end
    end
  end

  def caveats
    <<~EOS
      gocontentful -h
    EOS
  end

  test do
    system "#{bin}/gocontentful --version"
  end
end
