# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofana < Formula
  desc "CLI utility to manage Grafana resources"
  homepage "https://github.com/foomo/gofana"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gofana/releases/download/v0.1.1/gofana_0.1.1_darwin_amd64.tar.gz"
      sha256 "9586632bd410ff5f4dce89b97072d17dc40ba2bc9f841c44b4010b728326e391"

      def install
        bin.install "gofana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gofana/releases/download/v0.1.1/gofana_0.1.1_darwin_arm64.tar.gz"
      sha256 "191a873583439dc2d83e735e7155234f7310d931287f93b836843ea3c71d0b40"

      def install
        bin.install "gofana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gofana/releases/download/v0.1.1/gofana_0.1.1_linux_amd64.tar.gz"
      sha256 "d00e05709e1c4d906275c56b183b7434ce57293af231b6ddf8d6c7c7f8e9868f"
      def install
        bin.install "gofana"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gofana/releases/download/v0.1.1/gofana_0.1.1_linux_arm64.tar.gz"
      sha256 "ef4af073262e016045ace2a78ff701da0a516141d85ea298ef83a11112bff381"
      def install
        bin.install "gofana"
      end
    end
  end

  def caveats
    <<~EOS
      gofana --help
    EOS
  end

  test do
    system "#{bin}/gofana --version"
  end
end
