# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokazi < Formula
  desc "Simple daemonmless process manager"
  homepage "https://github.com/foomo/gokazi"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gokazi/releases/download/v0.1.6/gokazi_0.1.6_darwin_amd64.tar.gz"
      sha256 "776e6384241614f48cd4ea19e72a8ff7911b173b1dbb0883e7b4d7c86200f2fe"

      def install
        bin.install "gokazi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gokazi/releases/download/v0.1.6/gokazi_0.1.6_darwin_arm64.tar.gz"
      sha256 "dd3b8a0f9cdb2c147d70f941121e2255374a431a3521c8b4f71824696c677bf7"

      def install
        bin.install "gokazi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gokazi/releases/download/v0.1.6/gokazi_0.1.6_linux_amd64.tar.gz"
      sha256 "997177f43bbd3edd0380db86968034575a562a704d298a17d2945e6e17f5dd9a"
      def install
        bin.install "gokazi"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gokazi/releases/download/v0.1.6/gokazi_0.1.6_linux_arm64.tar.gz"
      sha256 "a2d9c8f4117cbdfb08874955c9500d5ecda2452c187c6dd7b2605af154e3bf3b"
      def install
        bin.install "gokazi"
      end
    end
  end

  def caveats
    <<~EOS
      gokazi -h
    EOS
  end

  test do
    system "#{bin}/gokazi --version"
  end
end
