# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokazi < Formula
  desc "Simple daemonmless process manager"
  homepage "https://github.com/foomo/gokazi"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gokazi/releases/download/v0.1.4/gokazi_0.1.4_darwin_amd64.tar.gz"
      sha256 "086d720d4648be67b43b7c91359706cf9fab63df5e072ec6b20734460ba45247"

      def install
        bin.install "gokazi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gokazi/releases/download/v0.1.4/gokazi_0.1.4_darwin_arm64.tar.gz"
      sha256 "677bac2bb7eddaa6d56b7c11a0aa9dc26739c40ee9a902ede49239e68ad2d5a7"

      def install
        bin.install "gokazi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foomo/gokazi/releases/download/v0.1.4/gokazi_0.1.4_linux_amd64.tar.gz"
        sha256 "243519423e83fed584cd0155c07d882f770e0f9dba3c0c66de8facc7870be2e8"

        def install
          bin.install "gokazi"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foomo/gokazi/releases/download/v0.1.4/gokazi_0.1.4_linux_arm64.tar.gz"
        sha256 "4fe97a5218e5978b2660e616346c21539d797ed2a022e70582b3b430b70c8ae0"

        def install
          bin.install "gokazi"
        end
      end
    end
  end

  def caveats
    <<~EOS
      gokazi -h
    EOS
  end

  test do
    system "#{bin}/gokazi --version"
  end
end
