# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokazi < Formula
  desc "Simple daemonmless process manager"
  homepage "https://github.com/foomo/gokazi"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gokazi/releases/download/v0.2.0/gokazi_0.2.0_darwin_amd64.tar.gz"
      sha256 "408b69dd1cdc647f683d041f7d0e2221d230ee06c5ab73bcad3f42001f6af356"

      define_method(:install) do
        bin.install "gokazi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gokazi/releases/download/v0.2.0/gokazi_0.2.0_darwin_arm64.tar.gz"
      sha256 "551dfa542953923d3027bb84835975720a6ae9d8a188da7525bc1328b4c682db"

      define_method(:install) do
        bin.install "gokazi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gokazi/releases/download/v0.2.0/gokazi_0.2.0_linux_amd64.tar.gz"
      sha256 "8ebc3e1a8c4b2c24eb0e3d042b4c53b873393f2b8ed809934a24f61fe05391bd"
      define_method(:install) do
        bin.install "gokazi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gokazi/releases/download/v0.2.0/gokazi_0.2.0_linux_arm64.tar.gz"
      sha256 "dc097275c9fe78de911d9b043b2809ea8745fec59815eca67c4da74172c46719"
      define_method(:install) do
        bin.install "gokazi"
      end
    end
  end

  def caveats
    <<~EOS
      gokazi -h
    EOS
  end

  test do
    system "#{bin}/gokazi --version"
  end
end
