# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotsrpc < Formula
  desc "CLI utility to generate go and typescript RPC calls easily"
  homepage "https://github.com/foomo/gotsrpc"
  version "2.8.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.8.0/gotsrpc_2.8.0_darwin_arm64.tar.gz"
      sha256 "c134811d6cbb44032b5f0c06e850af58844bacb2e1a9594be68a5db1b052bdf2"

      def install
        bin.install "gotsrpc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.8.0/gotsrpc_2.8.0_darwin_amd64.tar.gz"
      sha256 "4db3b7af942db434f9608fb553445897513996b6bf65172194d5981cb4e02ee1"

      def install
        bin.install "gotsrpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.8.0/gotsrpc_2.8.0_linux_amd64.tar.gz"
      sha256 "cfab96e161269646df3a2bc92e2a83dc8c20b89d1dabbfd73e27bcabb579848a"

      def install
        bin.install "gotsrpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/gotsrpc/releases/download/v2.8.0/gotsrpc_2.8.0_linux_arm64.tar.gz"
      sha256 "99d368ee0d8bf3839d193e631e4ba9359eb5d589778ae4c5273a322fc9cbe975"

      def install
        bin.install "gotsrpc"
      end
    end
  end

  def caveats
    <<~EOS
      gotsrpc gotsrpc.yml
    EOS
  end
end
