# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obacht < Formula
  desc "Security configuration scanner for developer environments"
  homepage "https://github.com/foomo/obacht"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/obacht/releases/download/v0.6.0/obacht_0.6.0_darwin_amd64.tar.gz"
      sha256 "ad7e2d0235d482a61c0623a8c627542e7aedd41f98f5c6ae160712d538eac903"

      define_method(:install) do
        bin.install "obacht"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/obacht/releases/download/v0.6.0/obacht_0.6.0_darwin_arm64.tar.gz"
      sha256 "b388f1c28e8a8bdc84cb6a317ea74c1a2dcd85c353522fb400f77727db3b2407"

      define_method(:install) do
        bin.install "obacht"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/obacht/releases/download/v0.6.0/obacht_0.6.0_linux_amd64.tar.gz"
      sha256 "641da4c33b0526f3d72c0f2a0a0c002de9f892f4d5c14b86ac6ac2e4ee84ad1c"
      define_method(:install) do
        bin.install "obacht"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/obacht/releases/download/v0.6.0/obacht_0.6.0_linux_arm64.tar.gz"
      sha256 "a9b2f0b8c124b5c4e63faaeb1dd518cba96165d3118a5f637f502c373435097c"
      define_method(:install) do
        bin.install "obacht"
      end
    end
  end

  def caveats
    <<~EOS
      obacht
    EOS
  end
end
