# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obacht < Formula
  desc "Security configuration scanner for developer environments"
  homepage "https://github.com/foomo/obacht"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/obacht/releases/download/v0.8.0/obacht_0.8.0_darwin_amd64.tar.gz"
      sha256 "893b5123ff8ee546b78c71f95a89cae4406e06fddbe83c16a375ded3b496e35e"

      define_method(:install) do
        bin.install "obacht"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/obacht/releases/download/v0.8.0/obacht_0.8.0_darwin_arm64.tar.gz"
      sha256 "3781454ab89ca0d451253f883f97478c8f306740cb2b5ee99498c7b9acbf4d45"

      define_method(:install) do
        bin.install "obacht"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/obacht/releases/download/v0.8.0/obacht_0.8.0_linux_amd64.tar.gz"
      sha256 "b0e1c47328417e8354da7009d346f1d263b12c8db9d4bcd77a8057eefffc05d8"
      define_method(:install) do
        bin.install "obacht"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/obacht/releases/download/v0.8.0/obacht_0.8.0_linux_arm64.tar.gz"
      sha256 "567c019e812d6939514a1fb03eb406b25d5173253cbd2fb5057c5fe9151d9fb8"
      define_method(:install) do
        bin.install "obacht"
      end
    end
  end

  def caveats
    <<~EOS
      obacht
    EOS
  end
end
