# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ownbrew < Formula
  desc "Your local project package manager"
  homepage "https://github.com/foomo/ownbrew"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/foomo/ownbrew/releases/download/v0.1.1/ownbrew_0.1.1_darwin_amd64.tar.gz"
      sha256 "a15ace0ea7fd1c0d893b35296bf3478143455b6a9994106228b501cede9ada39"

      def install
        bin.install "ownbrew"
      end
    end
    on_arm do
      url "https://github.com/foomo/ownbrew/releases/download/v0.1.1/ownbrew_0.1.1_darwin_arm64.tar.gz"
      sha256 "242460264fc9b2414c12ea1da08efc14bf5fbd137f357dbdcbd35d701f2e065f"

      def install
        bin.install "ownbrew"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foomo/ownbrew/releases/download/v0.1.1/ownbrew_0.1.1_linux_amd64.tar.gz"
        sha256 "19335a4579c99302132cb585ee1cb926913812e383aca192c77d7c2e070dfcd5"

        def install
          bin.install "ownbrew"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foomo/ownbrew/releases/download/v0.1.1/ownbrew_0.1.1_linux_arm64.tar.gz"
        sha256 "f2fb8ae29eb1ec1cae38a16724464afaddd297730536ecdc3f68c8dcdf86d1bc"

        def install
          bin.install "ownbrew"
        end
      end
    end
  end

  def caveats
    <<~EOS
      ownbrew --help
    EOS
  end
end
