# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ownbrew < Formula
  desc "Your local project package manager"
  homepage "https://github.com/foomo/ownbrew"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/ownbrew/releases/download/v0.2.2/ownbrew_0.2.2_darwin_amd64.tar.gz"
      sha256 "9eacf89873e29b5dbf1487d978bb2426cbae8f908e0518ac6b9ef9cf04adb3f5"

      def install
        bin.install "ownbrew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/ownbrew/releases/download/v0.2.2/ownbrew_0.2.2_darwin_arm64.tar.gz"
      sha256 "9797ea24d122c25d64de947eb0ea36dc22542ba4f51505351104066c6560cf2d"

      def install
        bin.install "ownbrew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foomo/ownbrew/releases/download/v0.2.2/ownbrew_0.2.2_linux_amd64.tar.gz"
        sha256 "21adbd92d9fd89d493139646c25f83e4e02e7c84f9b00a9fc58136ea0cf65cb6"

        def install
          bin.install "ownbrew"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foomo/ownbrew/releases/download/v0.2.2/ownbrew_0.2.2_linux_arm64.tar.gz"
        sha256 "71394d9964424e0e70b6c66a72375137b146e66328a2c708717ea8a29dc827d1"

        def install
          bin.install "ownbrew"
        end
      end
    end
  end

  def caveats
    <<~EOS
      ownbrew --help
    EOS
  end
end
