# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Posh < Formula
  desc "Project Oriented SHELL"
  homepage "https://github.com/foomo/posh"
  version "0.22.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/posh/releases/download/v0.22.0/posh_0.22.0_darwin_amd64.tar.gz"
      sha256 "36067e03abfcf8614a1bbc8343efd018a6ee5c0396271a922eb408a16b254485"

      define_method(:install) do
        bin.install "posh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/posh/releases/download/v0.22.0/posh_0.22.0_darwin_arm64.tar.gz"
      sha256 "15f57c59b0701a73b130fa0d76066463c8d99e2f07609bf3939bbe7bd4f8de8d"

      define_method(:install) do
        bin.install "posh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/posh/releases/download/v0.22.0/posh_0.22.0_linux_amd64.tar.gz"
      sha256 "9e51df708ae4f7b965fe193b48af243c0ab50429fc71653509de9a4591646bd0"
      define_method(:install) do
        bin.install "posh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/posh/releases/download/v0.22.0/posh_0.22.0_linux_arm64.tar.gz"
      sha256 "cec5100fe15d0556fa3e8e92a023665b6767296c2d705c5f987237dfda5c6a54"
      define_method(:install) do
        bin.install "posh"
      end
    end
  end

  def caveats
    <<~EOS
      posh help
    EOS
  end
end
