# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Posh < Formula
  desc "Project Oriented SHELL"
  homepage "https://github.com/foomo/posh"
  version "0.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/posh/releases/download/v0.21.0/posh_0.21.0_darwin_amd64.tar.gz"
      sha256 "c777e65e1533eb488e9270fcee69ce2b3fa7edc81325001885fccbf688bdc08d"

      define_method(:install) do
        bin.install "posh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/posh/releases/download/v0.21.0/posh_0.21.0_darwin_arm64.tar.gz"
      sha256 "10f8424fc496dda7c3d696bec10ab6a3a489c07ff59ac67abcb9d99a2dad97d0"

      define_method(:install) do
        bin.install "posh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/posh/releases/download/v0.21.0/posh_0.21.0_linux_amd64.tar.gz"
      sha256 "ad0c560cb53c4f87e03ee229d6c340e1f66e5e9ebbf2ab4f93bfd649f0987bab"
      define_method(:install) do
        bin.install "posh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/posh/releases/download/v0.21.0/posh_0.21.0_linux_arm64.tar.gz"
      sha256 "00c4dc41e8038469ef251e9fadc66345f53bb8fe7564b099ab8b7a5713d9e28d"
      define_method(:install) do
        bin.install "posh"
      end
    end
  end

  def caveats
    <<~EOS
      posh help
    EOS
  end
end
