# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SesamyCli < Formula
  desc "CLI utitlity to manage Server Side Tag Management"
  homepage "https://github.com/foomo/sesamy-cli"
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/foomo/sesamy-cli/releases/download/v0.3.1/sesamy-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "b3e83a4f2cd1a319afc2ab52845be9d71f54ccd05d644057144dc8a10bb18c2f"

      def install
        bin.install "sesamy"
      end
    end
    on_arm do
      url "https://github.com/foomo/sesamy-cli/releases/download/v0.3.1/sesamy-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "54330b5b2e083eb79c241fcfe1b3709150d52952c3427c1165bb782f606b441f"

      def install
        bin.install "sesamy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foomo/sesamy-cli/releases/download/v0.3.1/sesamy-cli_0.3.1_linux_amd64.tar.gz"
        sha256 "962b91fb12ab9f29a9da3b347692509b6182d581a5c101f7598a2dab1c848e67"

        def install
          bin.install "sesamy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/foomo/sesamy-cli/releases/download/v0.3.1/sesamy-cli_0.3.1_linux_arm64.tar.gz"
        sha256 "002c657ef6af2931d83458db583fece071417b7aa246366296edf88805409c78"

        def install
          bin.install "sesamy"
        end
      end
    end
  end

  def caveats
    <<~EOS
      sesamy --help
    EOS
  end
end
