# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadron < Formula
  desc "CLI utility manage infrastructure as code with helm"
  homepage "https://github.com/foomo/squadron"
  version "2.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/squadron/releases/download/v2.15.0/squadron_2.15.0_darwin_amd64.tar.gz"
      sha256 "96a251d456f5b1cbbbac5d346f2ca66ab9510f3eecd6c710504737ac4a8ec5b9"

      define_method(:install) do
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/squadron/releases/download/v2.15.0/squadron_2.15.0_darwin_arm64.tar.gz"
      sha256 "0f40089e1044748bba3e46363d977b0141363aa3859aea7176a1d9e59c458106"

      define_method(:install) do
        bin.install "squadron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/squadron/releases/download/v2.15.0/squadron_2.15.0_linux_amd64.tar.gz"
      sha256 "6199c1b3d02adb2feda10a195b59bd52742cb54e1b71df5c6a5c67d75f1f26e5"
      define_method(:install) do
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/squadron/releases/download/v2.15.0/squadron_2.15.0_linux_arm64.tar.gz"
      sha256 "f4029ac0b995e54537803fbb313785d7a22bb004e09167ef291a19be578b877e"
      define_method(:install) do
        bin.install "squadron"
      end
    end
  end

  def caveats
    <<~EOS
      squadron -h
    EOS
  end

  test do
    system "#{bin}/squadron version"
  end
end
