# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadron < Formula
  desc "CLI utility manage infrastructure as code with helm"
  homepage "https://github.com/foomo/squadron"
  version "2.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/squadron/releases/download/v2.12.0/squadron_2.12.0_darwin_amd64.tar.gz"
      sha256 "6f05b29ecd679cbd0ddfe0b41cf2048836ee032be419bbaf4cf915a71a008be0"

      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/squadron/releases/download/v2.12.0/squadron_2.12.0_darwin_arm64.tar.gz"
      sha256 "5ee4f350442201396469e842e8ffbe74b5c1c81fa876b93643556e1582d71067"

      def install
        bin.install "squadron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/squadron/releases/download/v2.12.0/squadron_2.12.0_linux_amd64.tar.gz"
      sha256 "a8ea60a4e3e153eac2d3684beced6d3ba05a98135f29a49f68cbe9ff8d149e6d"
      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/squadron/releases/download/v2.12.0/squadron_2.12.0_linux_arm64.tar.gz"
      sha256 "e1da5247b0728ee70e55340384a4772b227f12f52b4a557c22d2900c4747d3c7"
      def install
        bin.install "squadron"
      end
    end
  end

  def caveats
    <<~EOS
      squadron -h
    EOS
  end

  test do
    system "#{bin}/squadron version"
  end
end
