# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadron < Formula
  desc "CLI utility manage infrastructure as code with helm"
  homepage "https://github.com/foomo/squadron"
  version "2.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foomo/squadron/releases/download/v2.8.1/squadron_2.8.1_darwin_amd64.tar.gz"
      sha256 "23b7d13045ca2830ed675666b7312926731ca510b89573e01accb6771c3c74fb"

      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foomo/squadron/releases/download/v2.8.1/squadron_2.8.1_darwin_arm64.tar.gz"
      sha256 "ac4a905e65935490b7127cb0bd0232d8cc6c7c99a9ee297331a130b05572dc3b"

      def install
        bin.install "squadron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/squadron/releases/download/v2.8.1/squadron_2.8.1_linux_amd64.tar.gz"
      sha256 "4b62775c79e4e116ff22e5b0a8e1ce02f92203a23428b0286aa295f46533b1b8"
      def install
        bin.install "squadron"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/foomo/squadron/releases/download/v2.8.1/squadron_2.8.1_linux_arm64.tar.gz"
      sha256 "c7dd4a829534c0f973a01dd4ef2938ee29d6baf7011015cd27d928386f039da1"
      def install
        bin.install "squadron"
      end
    end
  end

  def caveats
    <<~EOS
      squadron -h
    EOS
  end

  test do
    system "#{bin}/squadron version"
  end
end
